Repository hmcts/pre-portal, pull requests merged in 2023-10, with the labels that each got.

#24 Feature: S28-1661 Recording Watch Page
  .yarn/install-state.gz
  angular/src/app/app-routing.module.ts
  angular/src/app/app.component.spec.ts
  angular/src/app/app.module.ts
  angular/src/app/components/watch-recording/watch-recording.component.ts
  angular/src/app/pages/browse-page/browse-page.component.spec.ts
  angular/src/app/pages/browse-page/browse-page.component.ts
  angular/src/app/pages/watch-page/watch-page.component.spec.ts
  angular/src/app/pages/watch-page/watch-page.component.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-24

#25 Feature: Open New Tab for all Footer Links
  angular/src/app/footer.component.spec.ts
  angular/src/app/footer.component.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-25

#26 Feature: Show Dummy Data
  angular/src/app/pages/browse-page/browse-page.component.spec.ts
  angular/src/app/pages/browse-page/browse-page.component.ts
  angular/src/app/pages/watch-page/watch-page.component.ts
  src/main/modules/helmet/index.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-26

#28 Feature: Hide Back Button on Terms and Conditions and Accessibility Statement Pages
  angular/src/app/components/back-link/back-link.component.spec.ts
  angular/src/app/components/back-link/back-link.component.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-28

#30 upgrade Node.js chart version
  charts/pre-portal/Chart.yaml
Labels: ns:pre, prd:pre, rel:pre-portal-pr-30
