Repository hmcts/pre-portal, pull requests merged in 2024-09, with the labels that each got.

#409 feat: change retry timings
  src/main/views/watch-mk.njk
Labels: ns:pre, prd:pre, enable_keep_helm, rel:pre-portal-pr-409

#443 Surpress expressjs dep vuln
  yarn-audit-known-issues
Labels: ns:pre, prd:pre, rel:pre-portal-pr-443

#445 Update Readme diagram with MK
  README.md
  yarn-audit-known-issues
Labels: ns:pre, prd:pre, rel:pre-portal-pr-445

#456 Debug messages for connecting to redis
  src/main/app/redis/RedisService.ts
  src/main/modules/auth/index.ts
  src/main/modules/properties-volume/index.ts
Labels: ns:pre, prd:pre, enable_keep_helm, rel:pre-portal-pr-456

#458 Fix: `/watch-mk` Page AMS Playback Failure
  src/main/modules/properties-volume/index.ts
  src/main/services/pre-api/pre-client.ts
  src/test/unit/pre-api-client.ts
Labels: ns:pre, prd:pre, enable_keep_helm, rel:pre-portal-pr-458

#462 Enable alerts on staging
  .yarn/cache/fsevents-patch-21ad2b1333-8.zip
  .yarn/cache/fsevents-patch-2882183fbf-8.zip
  infrastructure/data.tf
  infrastructure/exception-alert.tf
  infrastructure/liveness-alert.tf
  yarn-audit-known-issues
Labels: ns:pre, prd:pre, stg/add-or-update, prod/add-or-update, rel:pre-portal-pr-462

#449 S28-3208 increase retries
  src/main/views/watch-mk.njk
Labels: ns:pre, prd:pre, enable_keep_helm, rel:pre-portal-pr-449

#485 Get media kind player key from kv
  .yarn/cache/fsevents-patch-21ad2b1333-8.zip
  .yarn/cache/fsevents-patch-2882183fbf-8.zip
  charts/pre-portal/Chart.yaml
  charts/pre-portal/values.yaml
  config/default.json
  local.env
  src/main/modules/properties-volume/index.ts
  src/main/routes/watch-mk.ts
  src/main/views/watch-mk.njk
  src/test/unit/routes/browse.test.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-485

#486 Remove MK notice on page and added env var to switch watch to use MK …
  config/default.json
  local.env
  src/main/modules/properties-volume/index.ts
  src/main/routes/watch-mk.ts
  src/main/routes/watch.ts
  src/main/views/watch-mk.njk
Labels: ns:pre, prd:pre, rel:pre-portal-pr-486

#487 Can't overwrite config
  src/main/modules/properties-volume/index.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-487
