Repository hmcts/pre-portal, pull requests merged in 2024-03, with the labels that each got.

#97 Feature/playback
  charts/pre-portal/Chart.yaml
  charts/pre-portal/values.yaml
  config/default.json
  local.env
  src/main/app.ts
  src/main/modules/helmet/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/routes/browse.ts
  src/main/routes/watch.ts
  src/main/services/pre-api/pre-client.ts
  src/main/services/pre-api/types.ts
  src/main/views/watch.njk
  src/test/mock-api.ts
  src/test/routes/browse.ts
  src/test/routes/watch.ts
  src/test/unit/pre-api-client.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-97

#105 Test KV
  charts/pre-portal/Chart.yaml
  charts/pre-portal/values.dev.template.yaml
  charts/pre-portal/values.yaml
  src/main/modules/properties-volume/index.ts
Labels: ns:pre, prd:pre, enable_keep_helm, do not merge, rel:pre-portal-pr-105

#108 Fix: flow key header name
  src/main/services/pre-api/pre-client.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-108

#110 Fix pre-api url
  config/default.json
  local.env
  src/main/app.ts
  src/main/modules/properties-volume/index.ts
Labels: ns:pre, prd:pre, enable_keep_helm, rel:pre-portal-pr-110

#119 Use different staging url for testing in stg
  charts/pre-portal/values.stg.template.yaml
  config/default.json
  src/main/modules/properties-volume/index.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-119

#120 Don't silent login
  src/main/modules/auth/index.ts
  src/main/routes/sign-in.ts
  src/main/views/sign-in.njk
  src/test/routes/accessibility-statement.ts
  src/test/routes/home.ts
  src/test/routes/sign-in.ts
  src/test/routes/terms-and-conditions.ts
Labels: ns:pre, prd:pre, enable_keep_helm, rel:pre-portal-pr-120

#121 Change port so as not to clash with pre-api
  Dockerfile
  README.md
  charts/pre-portal/Chart.yaml
  charts/pre-portal/values.yaml
  config/default.json
  docker-compose.yml
  src/main/modules/properties-volume/index.ts
  src/main/server.ts
  src/test/smoke/smoke.ts
Labels: ns:pre, prd:pre, enable_keep_helm, rel:pre-portal-pr-121

#126 simple health ft
  src/test/functional/features/browse.feature
  src/test/steps/common.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-126

#129 Fix PORTAL_URL in staging
  charts/pre-portal/Chart.yaml
  charts/pre-portal/values.stg.template.yaml
  charts/pre-portal/values.yaml
Labels: ns:pre, prd:pre, rel:pre-portal-pr-129

#131 Reset config for staging-staging
  charts/pre-portal/values.stg.template.yaml
  config/demo.json
  config/dev.json
  config/production.json
  config/staging.json
  config/stg.json
  config/test.json
Labels: ns:pre, prd:pre, rel:pre-portal-pr-131

#135 Fix for API url
  src/main/modules/properties-volume/index.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-135

#138 Auto refresh browse page every 5minutes
  src/main/views/browse.njk
Labels: ns:pre, prd:pre, rel:pre-portal-pr-138

#134 Feat/cookie banner
  src/main/routes/cookies.ts
  src/main/views/cookies.njk
  src/main/views/template.njk
  src/main/views/webpack/js.njk
Labels: ns:pre, prd:pre, rel:pre-portal-pr-134

#139 Add dynatrace.com to the CSP
  src/main/modules/helmet/index.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-139

#140 Redeem invites when it's a new user signing into the portal
  .yarn/cache/fsevents-patch-21ad2b1333-8.zip
  .yarn/cache/fsevents-patch-2882183fbf-8.zip
  .yarn/cache/fsevents-patch-8f8bff7336-8.zip
  config/test.json
  src/main/modules/auth/index.ts
  src/main/services/pre-api/pre-client.ts
  src/test/functional/features/browse.feature
  src/test/functional/features/health.feature
  src/test/unit/modules/auth/index.test.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-140

#147 Missing REDIS_HOST config
  src/main/modules/properties-volume/index.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-147

#148 Set cookie attributes and update cookie page info
  src/main/modules/helmet/index.ts
  src/main/views/cookies.njk
  src/main/views/template.njk
  src/main/views/webpack/js.njk
Labels: ns:pre, prd:pre, rel:pre-portal-pr-148

#150 Fix: set page titles
  local.env
  src/main/views/accessibility-statement.njk
  src/main/views/browse.njk
  src/main/views/cookies.njk
  src/main/views/error.njk
  src/main/views/not-found.njk
  src/main/views/template.njk
  src/main/views/terms-and-conditions.njk
  src/main/views/watch.njk
Labels: ns:pre, prd:pre, rel:pre-portal-pr-150

#151 Dynatrace rum needs to be turn offable
  .pnp.cjs
  .yarn/cache/@hmcts-cookie-manager-npm-1.0.0-f7ac279484-7b9aacd551.zip
  jest.config.js
  package.json
  sonar-project.properties
  src/main/assets/js/cookie.js
  src/main/assets/js/index.ts
  src/main/modules/helmet/index.ts
  src/main/views/cookies.njk
  src/main/views/template.njk
  src/main/views/webpack/js.njk
  src/test/a11y/a11y.ts
  src/test/functional/features/browse.feature
  yarn.lock
Labels: ns:pre, prd:pre, enable_keep_helm, rel:pre-portal-pr-151

#154 Use test AMS instead of dev
  config/default.json
Labels: ns:pre, prd:pre, rel:pre-portal-pr-154

#157 Send portal access id to api
  jest.config.js
  src/main/routes/browse.ts
  src/main/routes/watch.ts
  src/main/services/pre-api/pre-client.ts
  src/main/services/session-user/session-user.ts
  src/main/types/access-status.ts
  src/main/types/user-profile.ts
  src/test/unit/modules/auth/index.test.ts
  src/test/unit/pre-api-client.ts
  src/test/unit/routes/browse.test.ts
  src/test/unit/routes/watch.test.ts
  src/test/unit/session-user/session-user.test.ts
  src/test/unit/test-helper.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-157

#158 Fix: pagination
  src/main/routes/browse.ts
  src/main/views/browse.njk
Labels: ns:pre, prd:pre, rel:pre-portal-pr-158

#162 Render the error message from default error handler
  src/main/app.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-162

#159 Check for portal_access object when logging in
  src/main/services/pre-api/pre-client.ts
  src/test/unit/pre-api-client.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-159

#167 Fix: manifest 404
  src/main/assets/manifest.json
  webpack/govukFrontend.js
Labels: ns:pre, prd:pre, rel:pre-portal-pr-167

#168 Fix: helmet cross origin embeds
  src/main/modules/helmet/index.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-168

#169 Proper healthcheck
  .yarn/cache/fsevents-patch-21ad2b1333-8.zip
  .yarn/cache/fsevents-patch-2882183fbf-8.zip
  .yarn/cache/fsevents-patch-8f8bff7336-8.zip
  sonar-project.properties
  src/main/routes/health.ts
  src/main/services/pre-api/pre-client.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-169

#173 Add axios vuln to known issues as using latest version
  .pnp.cjs
  .yarn/cache/axios-debug-log-npm-0.8.4-75c4d61990-529222882e.zip
  .yarn/cache/axios-debug-log-npm-1.0.0-b3208ab9aa-db41f20439.zip
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pre, prd:pre, rel:pre-portal-pr-173

#180 Show confirmation box when saving preferences on Cookie page
  src/main/assets/js/cookie.js
  src/main/assets/scss/main.scss
  src/main/views/cookies.njk
  src/main/views/template.njk
Labels: ns:pre, prd:pre, rel:pre-portal-pr-180

#181 Check users profile is active when loading session
  src/main/routes/browse.ts
  src/main/routes/watch.ts
  src/main/services/session-user/session-user.ts
  src/test/unit/session-user/session-user.test.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-181

#179 Wait for load video on watch page
  src/main/routes/watch.ts
  src/main/services/pre-api/pre-client.ts
  src/main/views/watch.njk
  src/test/mock-api.ts
  src/test/unit/pre-api-client.ts
  src/test/unit/routes/watch.test.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-179

#184 Use the api user profile for display name
  src/main/routes/browse.ts
  src/main/services/session-user/session-user.ts
  src/main/views/browse.njk
  src/test/unit/routes/browse.test.ts
  src/test/unit/session-user/session-user.test.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-184

#185 Replace section 28 with pre-recorded
  src/main/views/terms-and-conditions.njk
Labels: ns:pre, prd:pre, rel:pre-portal-pr-185

#188 Fix invited logic
  src/main/modules/auth/index.ts
  src/main/services/pre-api/pre-client.ts
  src/main/types/user-profile.ts
  src/test/unit/pre-api-client.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-188

#187 fix: loading gif
  src/main/assets/scss/main.scss
  src/main/views/watch.njk
Labels: ns:pre, prd:pre, rel:pre-portal-pr-187

#189 Format error page and fix bug with newly registered users
  .yarn/cache/fsevents-patch-21ad2b1333-8.zip
  .yarn/cache/fsevents-patch-2882183fbf-8.zip
  .yarn/cache/fsevents-patch-8f8bff7336-8.zip
  src/main/app.ts
  src/main/routes/browse.ts
  src/main/routes/watch.ts
  src/main/services/pre-api/pre-client.ts
  src/main/views/error.njk
  src/test/unit/modules/auth/index.test.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-189

#194 Fix: pagination (again)
  src/main/routes/browse.ts
  src/test/unit/routes/browse.test.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-194

#198 fix: redirect to /login if state not set
  src/main/app.ts
  src/main/views/error.njk
Labels: ns:pre, prd:pre, rel:pre-portal-pr-198

#199 Fix invites, logout and error messages
  charts/pre-portal/Chart.yaml
  charts/pre-portal/values.dev.template.yaml
  charts/pre-portal/values.stg.template.yaml
  charts/pre-portal/values.yaml
  config/default.json
  local.env
  src/main/modules/auth/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/services/pre-api/pre-client.ts
  src/main/views/error.njk
  src/test/unit/modules/auth/index.test.ts
  src/test/unit/pre-api-client.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-199

#204 Provide logout redirect param
  src/main/modules/auth/index.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-204

#207 allow users who logged in through b2c but aren't in portal to logout
  src/main/services/pre-api/pre-client.ts
  src/main/views/error.njk
  src/test/unit/pre-api-client.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-207

#208 Load session secret from KV in higher envs
  src/main/modules/properties-volume/index.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-208

#209 Wrong enum values
  src/main/services/pre-api/pre-client.ts
  src/main/types/access-status.ts
  src/main/types/user-profile.ts
  src/test/unit/modules/auth/index.test.ts
  src/test/unit/pre-api-client.ts
Labels: ns:pre, prd:pre, enable_keep_helm, rel:pre-portal-pr-209

#214 Change AMS config per env
  config/default.json
  src/main/modules/properties-volume/index.ts
  yarn-audit-known-issues
Labels: ns:pre, prd:pre, rel:pre-portal-pr-214

#215 Updated Readme
  README.md
Labels: ns:pre, prd:pre, rel:pre-portal-pr-215

#219 Update yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:pre, prd:pre, rel:pre-portal-pr-219

#218 Couple of Readme updates
  README.md
Labels: ns:pre, prd:pre, rel:pre-portal-pr-218

#222 fix: video focus, press space to play/pause
  src/main/views/watch.njk
Labels: ns:pre, prd:pre, rel:pre-portal-pr-222

#227 Update audit known issues
  yarn-audit-known-issues
Labels: ns:pre, prd:pre, rel:pre-portal-pr-227

#226 Check portal status every session load
  src/main/services/pre-api/pre-client.ts
  src/main/services/session-user/session-user.ts
  src/main/views/error.njk
  src/test/unit/pre-api-client.ts
  src/test/unit/session-user/session-user.test.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-226

#232 Remove link to homepage when user tries to login with no invitation
  .yarn/cache/fsevents-patch-21ad2b1333-8.zip
  .yarn/cache/fsevents-patch-2882183fbf-8.zip
  .yarn/cache/fsevents-patch-8f8bff7336-8.zip
  src/main/views/error.njk
Labels: ns:pre, prd:pre, rel:pre-portal-pr-232

#233 Update sign in error message
  src/main/services/pre-api/pre-client.ts
  src/main/views/error.njk
  src/test/unit/pre-api-client.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-233
