Repository hmcts/pre-portal, pull requests merged in 2024-04, with the labels that each got.

#236 Yarn audit fix
  yarn-audit-known-issues
Labels: ns:pre, prd:pre, rel:pre-portal-pr-236

#243 fix: yarn audit
  .yarn/cache/fsevents-patch-21ad2b1333-8.zip
  .yarn/cache/fsevents-patch-2882183fbf-8.zip
  .yarn/cache/fsevents-patch-8f8bff7336-8.zip
  yarn-audit-known-issues
Labels: ns:pre, prd:pre, rel:pre-portal-pr-243

#266 Feature: Add Audit for Recording Playback
  .pnp.cjs
  .yarn/cache/@types-uuid-npm-9.0.8-3eeeaa5abb-b8c60b7ba8.zip
  package.json
  src/main/routes/watch.ts
  src/main/services/pre-api/pre-client.ts
  src/main/services/pre-api/types.ts
  src/test/mock-api.ts
  src/test/unit/pre-api-client.ts
  src/test/unit/routes/watch.test.ts
  yarn.lock
Labels: ns:pre, prd:pre, rel:pre-portal-pr-266

#276 Allows for 50 PRs to be made in the next 24hours and be registered with B2C
  .github/workflows/b2c-callback-urls.yaml
Labels: ns:pre, prd:pre, rel:pre-portal-pr-276

#280 Use array instead of string to build redirect_uris
  .github/workflows/b2c-callback-urls.yaml
Labels: ns:pre, prd:pre, rel:pre-portal-pr-280

#282 Fix for b2c callback url workflow
  .github/workflows/b2c-callback-urls.yaml
Labels: ns:pre, prd:pre, rel:pre-portal-pr-282

#285 S28-2850: update pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ns:pre, prd:pre, rel:pre-portal-pr-285

#283 More feature tests
  src/test/functional/features/logged-in-footer.feature
  src/test/functional/features/logged-out.feature
  src/test/functional/features/login-error.feature
  src/test/steps/common.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-283

#305 Improved error message when there is a 403
  src/main/views/error.njk
Labels: ns:pre, prd:pre, rel:pre-portal-pr-305

#291 Fix: Recording Playback Add More Details
  .yarn/cache/fsevents-patch-21ad2b1333-8.zip
  .yarn/cache/fsevents-patch-2882183fbf-8.zip
  .yarn/cache/fsevents-patch-8f8bff7336-8.zip
  src/main/routes/watch.ts
  src/main/services/pre-api/types.ts
  src/main/views/error.njk
  src/test/mock-api.ts
  src/test/unit/routes/watch.test.ts
Labels: ns:pre, prd:pre, enable_keep_helm, rel:pre-portal-pr-291
