Repository hmcts/pre-portal, pull requests merged in 2025-08, with the labels that each got.

#826 S28 3692: Remove Unused Config
  charts/pre-portal/Chart.yaml
  charts/pre-portal/values.dev.template.yaml
  charts/pre-portal/values.stg.template.yaml
  charts/pre-portal/values.yaml
  config/default.json
  local.env
  src/main/modules/properties-volume/index.ts
  src/main/routes/browse.ts
  src/main/routes/watch.ts
  src/main/services/pre-api/pre-client.ts
  src/main/views/browse.njk
  src/main/views/watch.njk
Labels: ns:pre, prd:pre, enable_keep_helm, rel:pre-portal-pr-826

#935 Manual upgrade for allure-commandline
  package.json
  yarn.lock
Labels: ns:pre, prd:pre, rel:pre-portal-pr-935

#937 Manually upgrade lint-staged package
  .pnp.cjs
  .yarn/cache/commander-npm-14.0.0-1e0a7932ab-c05418bfc3.zip
  .yarn/cache/execa-npm-8.0.1-0211bd404c-d2ab5fe1e2.zip
  .yarn/cache/get-stream-npm-8.0.1-c921b4840e-dde5511e2e.zip
  .yarn/cache/human-signals-npm-5.0.0-ed25a9f58c-30f8870d83.zip
  .yarn/cache/is-stream-npm-3.0.0-a77ac9a62e-172093fe99.zip
  .yarn/cache/lint-staged-npm-15.5.2-5de9f8ff0d-523c332d6c.zip
  .yarn/cache/lint-staged-npm-16.1.4-fbe673094c-71330be72e.zip
  .yarn/cache/listr2-npm-8.3.3-378fa43619-92f1bb60e9.zip
  .yarn/cache/listr2-npm-9.0.1-6f1beb3bb9-ac5f98317f.zip
  .yarn/cache/mimic-fn-npm-4.0.0-feaeda79f7-995dcece15.zip
  .yarn/cache/nano-spawn-npm-1.0.2-030f0eb41e-6ce9e60846.zip
  .yarn/cache/npm-run-path-npm-5.3.0-193efca236-ae8e7a89da.zip
  .yarn/cache/onetime-npm-6.0.0-4f3684e29a-0846ce78e4.zip
  .yarn/cache/path-key-npm-4.0.0-2bce99f089-8e6c314ae6.zip
  .yarn/cache/strip-final-newline-npm-3.0.0-7972cbec8b-23ee263adf.zip
  package.json
  yarn.lock
Labels: ns:pre, prd:pre, rel:pre-portal-pr-937

#941 Manually upgrade dotenv package
  .pnp.cjs
  .yarn/cache/dotenv-npm-16.6.1-01334288ea-1d18971443.zip
  .yarn/cache/dotenv-npm-17.2.1-33fbb0afbc-8fde672d1c.zip
  package.json
  yarn.lock
Labels: ns:pre, prd:pre, rel:pre-portal-pr-941

#874 Wait a bit longer for video playback to load
  src/test/steps/common.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-874

#963 Tell devs where to find B2C code
  README.md
Labels: ns:pre, prd:pre, rel:pre-portal-pr-963

#848 S28 3939: Add CSV Upload in Admin Area for Automated Editing
  .pnp.cjs
  .yarn/cache/@types-multer-npm-1.4.12-1ec6cd63ed-719cacf88e.zip
  .yarn/cache/append-field-npm-1.0.0-bb98be199c-482ba08acc.zip
  .yarn/cache/busboy-npm-1.6.0-ebb5cbb04b-32801e2c01.zip
  .yarn/cache/concat-stream-npm-2.0.0-8bb2ad5aa0-d7f75d48f0.zip
  .yarn/cache/multer-npm-2.0.1-6192e70742-bcbc523108.zip
  .yarn/cache/streamsearch-npm-1.1.0-fc3ad6536d-1cce16cea8.zip
  .yarn/cache/typedarray-npm-0.0.6-37638b2241-33b39f3d0e.zip
  charts/pre-portal/Chart.yaml
  package.json
  src/main/modules/nunjucks/index.ts
  src/main/routes/admin/edits.ts
  src/main/services/pre-api/pre-client.ts
  src/main/services/pre-api/types.ts
  src/main/utils/helpers.ts
  src/main/views/admin/edits.njk
  src/main/views/template.njk
  src/test/unit/pre-api-client.test.ts
  src/test/unit/routes/admin/edits.test.ts
  src/test/unit/utils/helpers.test.ts
  yarn.lock
Labels: ns:pre, prd:pre, enable_keep_helm, stg/add-or-update, prod/add-or-update, rel:pre-portal-pr-848
