Repository hmcts/pre-portal, pull requests merged in 2025-02, with the labels that each got.

#710 Check for apm === true rather than 'on'
  src/main/assets/js/cookie.js
Labels: ns:pre, prd:pre, rel:pre-portal-pr-710

#691 S28 3635/disabled user fix
  .pnp.cjs
  src/main/routes/browse.ts
  src/main/routes/watch.ts
  src/test/unit/routes/browse.test.ts
  src/test/unit/routes/watch-no-user.test.ts
  src/test/unit/test-helper.ts
Labels: ns:pre, prd:pre, enable_keep_helm, rel:pre-portal-pr-691

#711 Move to OCI base chart
  charts/pre-portal/Chart.yaml
Labels: ns:pre, prd:pre, rel:pre-portal-pr-711

#721 Was correct before...
  src/main/assets/js/cookie.js
Labels: ns:pre, prd:pre, rel:pre-portal-pr-721

#722 Revert "S28 3635/disabled user fix"
  src/main/routes/browse.ts
  src/main/routes/watch.ts
  src/test/unit/routes/browse.test.ts
  src/test/unit/routes/watch-no-user.test.ts
  src/test/unit/test-helper.ts
Labels: ns:pre, prd:pre, enable_keep_helm, rel:pre-portal-pr-722

#726 Don't call next after catching global error
  .yarn/cache/@parcel-watcher-darwin-x64-npm-2.5.0-4c4c1c789c-8.zip
  .yarn/cache/@parcel-watcher-linux-x64-glibc-npm-2.5.0-32a578ae14-8.zip
  .yarn/cache/fsevents-patch-21ad2b1333-8.zip
  .yarn/cache/fsevents-patch-2882183fbf-8.zip
  src/main/app.ts
Labels: ns:pre, prd:pre, enable_keep_helm, rel:pre-portal-pr-726
