Repository hmcts/pre-portal, pull requests merged in 2025-01, with the labels that each got.

#668 Dynatrace prod
  src/main/modules/helmet/index.ts
Labels: ns:pre, prd:pre, rel:pre-portal-pr-668

#577 S28-3320: add static files for invite email
  src/main/assets/files/faqs.pdf
  src/main/assets/files/process-guide.pdf
  src/main/assets/files/user-guide.pdf
  webpack/customAssets.js
Labels: ns:pre, prd:pre, enable_keep_helm, rel:pre-portal-pr-577

#681 Remove redundant ITHC env from Jenkinsfile_CNP
  Jenkinsfile_CNP
Labels: ns:pre, prd:pre

#682 Move dynatrace tag to head element
  .yarn/cache/@parcel-watcher-darwin-x64-npm-2.5.0-4c4c1c789c-8.zip
  .yarn/cache/@parcel-watcher-linux-x64-glibc-npm-2.5.0-32a578ae14-8.zip
  .yarn/cache/fsevents-patch-21ad2b1333-8.zip
  .yarn/cache/fsevents-patch-2882183fbf-8.zip
  src/main/views/template.njk
Labels: ns:pre, prd:pre

#690 Update static files
  src/main/assets/files/faqs.pdf
  src/main/assets/files/user-guide.pdf
Labels: ns:pre, prd:pre

#698 S28 3478: not found page changes
  src/main/views/not-found.njk
  src/test/functional/features/admin.feature
  src/test/unit/routes/admin.ts
Labels: ns:pre, prd:pre, enable_keep_helm, rel:pre-portal-pr-698
