Repository hmcts/pre-portal, pull requests merged in 2025-06, with the labels that each got.

#840 Adds a standard web test and monitor for b2c sign in
  infrastructure/demo.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
  infrastructure/web-test.tf
Labels: ns:pre, prd:pre, stg/add-or-update, prod/add-or-update, rel:pre-portal-pr-840

#844 Remove dimension block from alert
  infrastructure/web-test.tf
Labels: ns:pre, prd:pre, stg/add-or-update, prod/add-or-update, rel:pre-portal-pr-844

#845 Add action group to demo to test alerts
  infrastructure/data.tf
Labels: ns:pre, prd:pre, stg/add-or-update, prod/add-or-update, rel:pre-portal-pr-845

#849 Fix web test
  infrastructure/web-test.tf
Labels: ns:pre, prd:pre, stg/add-or-update, prod/add-or-update, rel:pre-portal-pr-849

#868 Remove mocha
  .pnp.cjs
  .yarn/cache/@types-mocha-npm-10.0.10-1e025e7c6e-17a56add60.zip
  .yarn/cache/dateformat-npm-4.6.3-aa1a4cb7f9-c3aa0617c0.zip
  .yarn/cache/diff-npm-7.0.0-dcfd888f89-5db0d33947.zip
  .yarn/cache/fs-extra-npm-10.1.0-86573680ed-dc94ab3709.zip
  .yarn/cache/fsu-npm-1.1.1-79f8a4b9ea-470564b758.zip
  .yarn/cache/lodash.isempty-npm-4.4.0-9997a8300c-a8118f23f7.zip
  .yarn/cache/lodash.isfunction-npm-3.0.9-72aaa7f66c-99e54c34b1.zip
  .yarn/cache/lodash.isobject-npm-3.0.2-ec19461220-6c1667cbc4.zip
  .yarn/cache/mocha-npm-11.6.0-6b8c5f310b-5414b5ffad.zip
  .yarn/cache/mochawesome-merge-npm-5.0.0-20701a10b3-445d6978fa.zip
  .yarn/cache/mochawesome-npm-7.1.3-17afbbd4e0-87730026de.zip
  .yarn/cache/mochawesome-report-generator-npm-6.2.0-8649ea3e3d-bbfafc781a.zip
  .yarn/cache/opener-npm-1.5.2-7a1aa69f14-33b620c0d5.zip
  .yarn/cache/prop-types-npm-15.8.1-17c71ee7ee-c056d3f1c0.zip
  .yarn/cache/react-is-npm-16.13.1-a9b9382b4f-f7a19ac349.zip
  .yarn/cache/tcomb-npm-3.2.29-9790a26d8e-484e39a06c.zip
  .yarn/cache/tcomb-validation-npm-3.4.1-51eeb26a6a-0b0bc3dab6.zip
  .yarn/cache/validator-npm-13.15.15-143146ad19-10c1b9215a.zip
  .yarn/cache/workerpool-npm-9.3.2-264c284a0a-da39d0a92c.zip
  package.json
  yarn.lock
Labels: ns:pre, prd:pre, rel:pre-portal-pr-868

#879 Remove unused AppInsightsInstrumentationKey
  charts/pre-portal/Chart.yaml
  charts/pre-portal/values.yaml
Labels: ns:pre, prd:pre, rel:pre-portal-pr-879

#833 S28-3917 Readme Updates
  README.md
Labels: ns:pre, prd:pre, rel:pre-portal-pr-833
